# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelExtractedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.TextField(blank=True, null=True)),
                ('asset_location', models.TextField(blank=True, null=True)),
                ('asset_name', models.TextField(blank=True, null=True)),
                ('closed', models.TextField(blank=True, null=True)),
                ('department_name', models.TextField(blank=True, null=True)),
                ('failure_reason_id', models.TextField(blank=True, null=True)),
                ('failure_reason_name', models.TextField(blank=True, null=True)),
                ('labor_report', models.TextField(blank=True, null=True)),
                ('manufacturer_name', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('target_date', models.TextField(blank=True, null=True)),
                ('work_order', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
