# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parser_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
