# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parser_management', '0002_exceljobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceljobs',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'COMPLETED'), (3, 'ERROR')], default=1),
        ),
    ]
