# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('excel_parser_management', '0003_exceljobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceljobs',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
